spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/postgres
  data:
    redis:
      host: redis
      port: 6379
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${quotes.supplier} # уникальный id для instance
bcs:
  api:
    url: https://api.bcs.ru
    all-stocks: /partner/quotations?portfolio_ids%5B0%5D=115 # &limit=500 (параметр limit указывает кол-во акций, выгружаемых с BCS)
    partner-token: A5264D52-1510-4E42-8E90-E729FF405646
    one-stock: /udfdatafeed/v1/info?instruments={secureCode}&inOrderArray=true
webclient:
  timeout: 10000
tinkoff:
  api:
    token: t.qkfYsq60_C584svox3zRIqfXVMp7emIdZLYMTJIc2dHfr7Jtssh9pJ-WjJiO98IUPJTYWThbIUWb37SrGTMiNg
    sandbox: t.OlKXgNUlgSJ9X1JGcJ8J_ABQcVhJJ6wdMYTZB6Owyx0zqA5i1MoWPcm-3b1ma_XrZtj5OooL7AI2GEQXZgZeMg
    is-sandbox-mode: true
quotes:
  supplier: tinkoff # bcs or tinkoff
springdoc:
  swagger-ui:
    configUrl: /quotes/v3/api-docs/swagger-config
    url: /quotes/v3/api-docs
  api-docs:
    enabled: true